name: CAN log tools

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Test Compiler
        run: javac -version

      - name: Gradle
        run: ./gradlew test

      - name: Gradle
        run: ./gradlew jar

      - name: Upload .jar file
        uses: actions/upload-artifact@v2
        with:
          name: can-log-tools jar
          path: build/libs/can-log-tools-0.1-SNAPSHOT.jar
